version: "3"
services:
  traefik:
    image: traefik
    volumes:
    - ./traefik.toml:/etc/traefik/traefik.toml:z
    - /var/run/docker.sock:/var/run/docker.sock:z
    ports:
    - "80:80"
    - "443:442"
    
